# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: laptopService.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13laptopService.proto\x12\rlaptopService\"\x07\n\x05\x45mpty\"\x1f\n\x06Laptop\x12\x15\n\rserial_number\x18\x01 \x01(\x05\"\x19\n\x03\x41\x63k\x12\x12\n\nsuccessful\x18\x01 \x01(\x08\x32v\n\rLaptopService\x12\x32\n\x03\x62uy\x12\x14.laptopService.Empty\x1a\x15.laptopService.Laptop\x12\x31\n\x04sell\x12\x15.laptopService.Laptop\x1a\x12.laptopService.AckB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'laptopService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_EMPTY']._serialized_start=38
  _globals['_EMPTY']._serialized_end=45
  _globals['_LAPTOP']._serialized_start=47
  _globals['_LAPTOP']._serialized_end=78
  _globals['_ACK']._serialized_start=80
  _globals['_ACK']._serialized_end=105
  _globals['_LAPTOPSERVICE']._serialized_start=107
  _globals['_LAPTOPSERVICE']._serialized_end=225
# @@protoc_insertion_point(module_scope)
