# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from flask_mongo_grpc.grpc import service_pb2 as flask__mongo__grpc_dot_grpc_dot_service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in flask_mongo_grpc/grpc/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SensorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getSensors = channel.unary_stream(
                '/sensor_measurement.SensorService/getSensors',
                request_serializer=flask__mongo__grpc_dot_grpc_dot_service__pb2.Empty.SerializeToString,
                response_deserializer=flask__mongo__grpc_dot_grpc_dot_service__pb2.Sensor.FromString,
                _registered_method=True)
        self.getMean = channel.unary_unary(
                '/sensor_measurement.SensorService/getMean',
                request_serializer=flask__mongo__grpc_dot_grpc_dot_service__pb2.MeanRequest.SerializeToString,
                response_deserializer=flask__mongo__grpc_dot_grpc_dot_service__pb2.StringMessage.FromString,
                _registered_method=True)


class SensorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getSensors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMean(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getSensors': grpc.unary_stream_rpc_method_handler(
                    servicer.getSensors,
                    request_deserializer=flask__mongo__grpc_dot_grpc_dot_service__pb2.Empty.FromString,
                    response_serializer=flask__mongo__grpc_dot_grpc_dot_service__pb2.Sensor.SerializeToString,
            ),
            'getMean': grpc.unary_unary_rpc_method_handler(
                    servicer.getMean,
                    request_deserializer=flask__mongo__grpc_dot_grpc_dot_service__pb2.MeanRequest.FromString,
                    response_serializer=flask__mongo__grpc_dot_grpc_dot_service__pb2.StringMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sensor_measurement.SensorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sensor_measurement.SensorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SensorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getSensors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sensor_measurement.SensorService/getSensors',
            flask__mongo__grpc_dot_grpc_dot_service__pb2.Empty.SerializeToString,
            flask__mongo__grpc_dot_grpc_dot_service__pb2.Sensor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getMean(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sensor_measurement.SensorService/getMean',
            flask__mongo__grpc_dot_grpc_dot_service__pb2.MeanRequest.SerializeToString,
            flask__mongo__grpc_dot_grpc_dot_service__pb2.StringMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
