# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: magazzino.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'magazzino.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmagazzino.proto\x12\tmagazzino\"$\n\x04Item\x12\x0e\n\x06idItem\x18\x01 \x01(\x03\x12\x0c\n\x04type\x18\x02 \x01(\t\"\x1e\n\rStringMessage\x12\r\n\x05value\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\x9f\x01\n\tMagazzino\x12\x35\n\x08\x64\x65posita\x12\x0f.magazzino.Item\x1a\x18.magazzino.StringMessage\x12,\n\x07preleva\x12\x10.magazzino.Empty\x1a\x0f.magazzino.Item\x12-\n\x06svuota\x12\x10.magazzino.Empty\x1a\x0f.magazzino.Item0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'magazzino_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEM']._serialized_start=30
  _globals['_ITEM']._serialized_end=66
  _globals['_STRINGMESSAGE']._serialized_start=68
  _globals['_STRINGMESSAGE']._serialized_end=98
  _globals['_EMPTY']._serialized_start=100
  _globals['_EMPTY']._serialized_end=107
  _globals['_MAGAZZINO']._serialized_start=110
  _globals['_MAGAZZINO']._serialized_end=269
# @@protoc_insertion_point(module_scope)
