// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: magazzino.proto
// Protobuf Java Version: 4.31.1

package magazzino.grpc;

@com.google.protobuf.Generated
public final class Magazzino {
  private Magazzino() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Magazzino.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_magazzino_grpc_Articolo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_magazzino_grpc_Articolo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_magazzino_grpc_StringMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_magazzino_grpc_StringMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_magazzino_grpc_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_magazzino_grpc_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017magazzino.proto\022\016magazzino.grpc\"\026\n\010Art" +
      "icolo\022\n\n\002id\030\001 \001(\005\"\036\n\rStringMessage\022\r\n\005va" +
      "lue\030\001 \001(\t\"\007\n\005Empty2\223\001\n\020MagazzinoService\022" +
      "C\n\010deposita\022\030.magazzino.grpc.Articolo\032\035." +
      "magazzino.grpc.StringMessage\022:\n\007preleva\022" +
      "\025.magazzino.grpc.Empty\032\030.magazzino.grpc." +
      "ArticoloB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_magazzino_grpc_Articolo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_magazzino_grpc_Articolo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_magazzino_grpc_Articolo_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_magazzino_grpc_StringMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_magazzino_grpc_StringMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_magazzino_grpc_StringMessage_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_magazzino_grpc_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_magazzino_grpc_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_magazzino_grpc_Empty_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
