# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orderManager.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12orderManager.proto\x12\x0corderManager\"^\n\x05Order\x12\x0b\n\x03_id\x18\x01 \x01(\t\x12\r\n\x05items\x18\x02 \x03(\t\x12\x13\n\x0b\x64\x65scrizione\x18\x03 \x01(\t\x12\x0e\n\x06prezzo\x18\x04 \x01(\x02\x12\x14\n\x0c\x64\x65stinazione\x18\x05 \x01(\t\"i\n\x10\x43ombinedShipment\x12\x0b\n\x03_id\x18\x01 \x01(\t\x12\r\n\x05stato\x18\x02 \x01(\t\x12#\n\x06orders\x18\x03 \x03(\x0b\x32\x13.orderManager.Order\x12\x14\n\x0c\x64\x65stinazione\x18\x04 \x01(\t\"\x1e\n\rStringMessage\x12\r\n\x05value\x18\x01 \x01(\t2\xeb\x02\n\x13OrderManagerService\x12<\n\x08\x61\x64\x64Order\x12\x13.orderManager.Order\x1a\x1b.orderManager.StringMessage\x12<\n\x08getOrder\x12\x1b.orderManager.StringMessage\x1a\x13.orderManager.Order\x12\x42\n\x0csearchOrders\x12\x1b.orderManager.StringMessage\x1a\x13.orderManager.Order0\x01\x12H\n\rprocessOrders\x12\x13.orderManager.Order\x1a\x1e.orderManager.CombinedShipment(\x01\x30\x01\x12J\n\x0e\x63\x61ncelShipment\x12\x1b.orderManager.StringMessage\x1a\x1b.orderManager.StringMessageB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orderManager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_ORDER']._serialized_start=36
  _globals['_ORDER']._serialized_end=130
  _globals['_COMBINEDSHIPMENT']._serialized_start=132
  _globals['_COMBINEDSHIPMENT']._serialized_end=237
  _globals['_STRINGMESSAGE']._serialized_start=239
  _globals['_STRINGMESSAGE']._serialized_end=269
  _globals['_ORDERMANAGERSERVICE']._serialized_start=272
  _globals['_ORDERMANAGERSERVICE']._serialized_end=635
# @@protoc_insertion_point(module_scope)
