// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: magazzino.proto
// Protobuf Java Version: 4.31.1

package magazzinoExample.magazzino;

@com.google.protobuf.Generated
public interface ArticoloOrBuilder extends
    // @@protoc_insertion_point(interface_extends:magazzinoExample.magazzino.Articolo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
