// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: magazzino.proto
// Protobuf Java Version: 4.31.1

package magazzinoExample.magazzino;

@com.google.protobuf.Generated
public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:magazzinoExample.magazzino.Empty)
    com.google.protobuf.MessageOrBuilder {
}
