// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: magazzino.proto
// Protobuf Java Version: 4.31.1

package magazzinoExample.magazzino;

@com.google.protobuf.Generated
public final class MagazzinoOuterClass {
  private MagazzinoOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      MagazzinoOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_magazzinoExample_magazzino_Articolo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_magazzinoExample_magazzino_Articolo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_magazzinoExample_magazzino_Acknowledge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_magazzinoExample_magazzino_Acknowledge_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_magazzinoExample_magazzino_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_magazzinoExample_magazzino_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017magazzino.proto\022\032magazzinoExample.maga" +
      "zzino\"\026\n\010Articolo\022\n\n\002id\030\001 \001(\003\"\036\n\013Acknowl" +
      "edge\022\017\n\007message\030\001 \001(\t\"\007\n\005Empty2\272\001\n\tMagaz" +
      "zino\022Y\n\010deposita\022$.magazzinoExample.maga" +
      "zzino.Articolo\032\'.magazzinoExample.magazz" +
      "ino.Acknowledge\022R\n\007preleva\022!.magazzinoEx" +
      "ample.magazzino.Empty\032$.magazzinoExample" +
      ".magazzino.ArticoloB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_magazzinoExample_magazzino_Articolo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_magazzinoExample_magazzino_Articolo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_magazzinoExample_magazzino_Articolo_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_magazzinoExample_magazzino_Acknowledge_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_magazzinoExample_magazzino_Acknowledge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_magazzinoExample_magazzino_Acknowledge_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_magazzinoExample_magazzino_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_magazzinoExample_magazzino_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_magazzinoExample_magazzino_Empty_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
