# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flask_mongo_grpc/grpc/service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'flask_mongo_grpc/grpc/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#flask_mongo_grpc/grpc/service.proto\x12\x12sensor_measurement\"\x07\n\x05\x45mpty\"\'\n\x06Sensor\x12\x0b\n\x03_id\x18\x01 \x01(\x03\x12\x10\n\x08\x64\x61taType\x18\x02 \x01(\t\"2\n\x0bMeanRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\x03\x12\x10\n\x08\x64\x61taType\x18\x02 \x01(\t\"\x1e\n\rStringMessage\x12\r\n\x05value\x18\x01 \x01(\t2\xa5\x01\n\rSensorService\x12\x45\n\ngetSensors\x12\x19.sensor_measurement.Empty\x1a\x1a.sensor_measurement.Sensor0\x01\x12M\n\x07getMean\x12\x1f.sensor_measurement.MeanRequest\x1a!.sensor_measurement.StringMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flask_mongo_grpc.grpc.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=59
  _globals['_EMPTY']._serialized_end=66
  _globals['_SENSOR']._serialized_start=68
  _globals['_SENSOR']._serialized_end=107
  _globals['_MEANREQUEST']._serialized_start=109
  _globals['_MEANREQUEST']._serialized_end=159
  _globals['_STRINGMESSAGE']._serialized_start=161
  _globals['_STRINGMESSAGE']._serialized_end=191
  _globals['_SENSORSERVICE']._serialized_start=194
  _globals['_SENSORSERVICE']._serialized_end=359
# @@protoc_insertion_point(module_scope)
