// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: laptopService.proto
// Protobuf Java Version: 4.31.1

package laptopService.grpc;

@com.google.protobuf.Generated
public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:laptopService.grpc.Empty)
    com.google.protobuf.MessageOrBuilder {
}
