// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: laptopService.proto
// Protobuf Java Version: 4.31.1

package laptopService.grpc;

@com.google.protobuf.Generated
public final class LaptopServiceOuterClass {
  private LaptopServiceOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      LaptopServiceOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_laptopService_grpc_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_laptopService_grpc_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_laptopService_grpc_Laptop_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_laptopService_grpc_Laptop_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_laptopService_grpc_StringMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_laptopService_grpc_StringMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023laptopService.proto\022\022laptopService.grp" +
      "c\"\007\n\005Empty\"\037\n\006Laptop\022\025\n\rserial_number\030\001 " +
      "\001(\005\"\036\n\rStringMessage\022\r\n\005value\030\001 \001(\t2\224\001\n\r" +
      "LaptopService\022<\n\003buy\022\031.laptopService.grp" +
      "c.Empty\032\032.laptopService.grpc.Laptop\022E\n\004s" +
      "ell\022\032.laptopService.grpc.Laptop\032!.laptop" +
      "Service.grpc.StringMessageB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_laptopService_grpc_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_laptopService_grpc_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_laptopService_grpc_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_laptopService_grpc_Laptop_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_laptopService_grpc_Laptop_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_laptopService_grpc_Laptop_descriptor,
        new java.lang.String[] { "SerialNumber", });
    internal_static_laptopService_grpc_StringMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_laptopService_grpc_StringMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_laptopService_grpc_StringMessage_descriptor,
        new java.lang.String[] { "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
