// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: laptopService.proto
// Protobuf Java Version: 4.31.1

package laptopService.grpc;

@com.google.protobuf.Generated
public interface LaptopOrBuilder extends
    // @@protoc_insertion_point(interface_extends:laptopService.grpc.Laptop)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 serial_number = 1;</code>
   * @return The serialNumber.
   */
  int getSerialNumber();
}
