// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: laptopService.proto
// Protobuf Java Version: 4.31.1

package laptopService.grpc;

@com.google.protobuf.Generated
public interface StringMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:laptopService.grpc.StringMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
