# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: magazzino.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'magazzino.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmagazzino.proto\x12\x14\x64ispatcher.magazzino\"\x16\n\x08\x41rticolo\x12\n\n\x02id\x18\x01 \x01(\x03\"\x1e\n\x0b\x41\x63knowledge\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xa2\x01\n\tMagazzino\x12M\n\x08\x64\x65posita\x12\x1e.dispatcher.magazzino.Articolo\x1a!.dispatcher.magazzino.Acknowledge\x12\x46\n\x07preleva\x12\x1e.dispatcher.magazzino.Articolo\x1a\x1b.dispatcher.magazzino.EmptyB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'magazzino_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_ARTICOLO']._serialized_start=41
  _globals['_ARTICOLO']._serialized_end=63
  _globals['_ACKNOWLEDGE']._serialized_start=65
  _globals['_ACKNOWLEDGE']._serialized_end=95
  _globals['_EMPTY']._serialized_start=97
  _globals['_EMPTY']._serialized_end=104
  _globals['_MAGAZZINO']._serialized_start=107
  _globals['_MAGAZZINO']._serialized_end=269
# @@protoc_insertion_point(module_scope)
