# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: magazzino.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmagazzino.proto\x12\x0emagazzino.grpc\"\x16\n\x08\x41rticolo\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1e\n\rStringMessage\x12\r\n\x05value\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\x93\x01\n\x10MagazzinoService\x12\x43\n\x08\x64\x65posita\x12\x18.magazzino.grpc.Articolo\x1a\x1d.magazzino.grpc.StringMessage\x12:\n\x07preleva\x12\x15.magazzino.grpc.Empty\x1a\x18.magazzino.grpc.ArticoloB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'magazzino_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_ARTICOLO']._serialized_start=35
  _globals['_ARTICOLO']._serialized_end=57
  _globals['_STRINGMESSAGE']._serialized_start=59
  _globals['_STRINGMESSAGE']._serialized_end=89
  _globals['_EMPTY']._serialized_start=91
  _globals['_EMPTY']._serialized_end=98
  _globals['_MAGAZZINOSERVICE']._serialized_start=101
  _globals['_MAGAZZINOSERVICE']._serialized_end=248
# @@protoc_insertion_point(module_scope)
