# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: laptopService.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13laptopService.proto\x12\x12laptopService.grpc\"\x07\n\x05\x45mpty\"\x1f\n\x06Laptop\x12\x15\n\rserial_number\x18\x01 \x01(\x05\"\x1e\n\rStringMessage\x12\r\n\x05value\x18\x01 \x01(\t2\x94\x01\n\rLaptopService\x12<\n\x03\x62uy\x12\x19.laptopService.grpc.Empty\x1a\x1a.laptopService.grpc.Laptop\x12\x45\n\x04sell\x12\x1a.laptopService.grpc.Laptop\x1a!.laptopService.grpc.StringMessageB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'laptopService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_EMPTY']._serialized_start=43
  _globals['_EMPTY']._serialized_end=50
  _globals['_LAPTOP']._serialized_start=52
  _globals['_LAPTOP']._serialized_end=83
  _globals['_STRINGMESSAGE']._serialized_start=85
  _globals['_STRINGMESSAGE']._serialized_end=115
  _globals['_LAPTOPSERVICE']._serialized_start=118
  _globals['_LAPTOPSERVICE']._serialized_end=266
# @@protoc_insertion_point(module_scope)
